import {
  Project,
  IssueAddressed,
  ProjectState,
  ProjectType,
  ProjectRegion,
  ProjectFrequency,
  VolunteerRequirementType,
} from 'models/Project';

import {
  seedData,
  getProjectOwner,
  connectMongoose,
  closeMongooseConnection,
} from './utils';

connectMongoose();

getProjectOwner()
  .then(async (projectOwner) => {
    if (!projectOwner) {
      console.log('Please seed Project Owners first');
      return;
    }
    const volunteerRequirementAttributes = [
      {
        type: [VolunteerRequirementType.INTERACTION],
        commitmentLevel: 'Once a Week',
        number: 5,
      },
      {
        type: [VolunteerRequirementType.OTHERS_ADHOC],
        commitmentLevel: 'As and when needed',
        number: 1,
      },
    ];

    const projectAttributes = [
      {
        title: 'Save the Earth',
        description:
          'Cat ipsum dolor sit amet, malkin yet donskoy for havana brown or balinese . American shorthair. Balinese bobcat or himalayan yet bombay. Lion panther thai. Persian british shorthair so himalayan and panther and norwegian forest and bengal. Bobcat maine coon bobcat, yet birman. Scottish fold bombay himalayan lion bombay abyssinian . Russian blue. Donskoy maine coon. Siamese lynx. Cougar tiger devonshire rex. Egyptian mau. Grimalkin persian. Burmese thai himalayan bobcat. Cornish',
        volunteerSignupUrl: 'http://www.techladies.co/',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.LAND_AND_NOISE_POLLUTION, IssueAddressed.WASTE],
        volunteerRequirementsDescription:
          'Kitten tiger malkin egyptian mau. Lynx tomcat for ragdoll. Tomcat ocelot and tabby. Savannah grimalkin and jaguar yet siberian. Malkin american shorthair turkish angora manx. Cornish rex cornish rex and norwegian forest.',
        volunteerBenefitsDescription:
          'Turkish angora siamese. Puma. Scottish fold. Bobcat ocicat. Kitty bombay.',
        projectType: ProjectType.EVENT,
        time: '09:00',
        region: ProjectRegion.CENTRAL,
        address: '12 Nice Road, #05-04, Singapore 101942',
        state: ProjectState.APPROVED_INACTIVE,
        startDate: new Date(2018, 12, 1),
        endDate: new Date(2018, 12, 2),
        frequency: ProjectFrequency.ONCE_A_WEEK,
      },
      {
        title: 'Cat Adoption Drive',
        description: 'Save the earth description',
        volunteerSignupUrl: '',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.AWARENESS_AND_EDUCATION],
        volunteerRequirementsDescription: 'Etiam nec mauris at dui vestibulum tincidunt.',
        volunteerBenefitsDescription: 'Maecenas a tristique sapien. Proin luctus tincidunt mi, et laoreet ex varius congue. Praesent risus nulla, vulputate eu cursus ut, condimentum vitae risus.',
        projectType: ProjectType.EVENT,
        time: '14:00',
        region: ProjectRegion.WEST,
        state: ProjectState.PENDING_APPROVAL,
        startDate: new Date(2018, 10, 1),
        endDate: new Date(2018, 10, 1),
        frequency: ProjectFrequency.ONCE_A_WEEK,
      },
      {
        title: 'Greenland Project',
        description: 'Greenland Project description',
        volunteerSignupUrl: 'google.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WASTE, IssueAddressed.GREEN_LIFESTYLE],
        volunteerRequirementsDescription: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.',
        volunteerBenefitsDescription: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.',
        projectType: ProjectType.RECURRING,
        time: '09:00',
        region: ProjectRegion.WEST,
        state: ProjectState.REJECTED,
        frequency: ProjectFrequency.A_FEW_TIMES_A_YEAR,
        rejectionReason:
          'Lorem ipsum dolor sit amet, id commodo invidunt persecuti nam, id alienum deserunt urbanitas eam, denique elaboraret definitiones eum at. Mea cu maluisset deseruisse, phaedrum honestatis ius ex. Sed id novum melius consulatu. No cum menandri adipiscing, ei vocent persius mei. Ex vis mutat fastidii.',
      },
      {
        title: 'Singing in the Rain',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In varius imperdiet laoreet. Maecenas eu tempor orci, et feugiat metus. Ut consequat libero sed bibendum mollis. Cras in ipsum id purus volutpat maximus ac commodo sem. Pellentesque magna eros, facilisis in urna id, luctus suscipit turpis.',
        volunteerSignupUrl: 'nus.edu.sg',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.ENERGY, IssueAddressed.OTHER],
        volunteerRequirementsDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In varius imperdiet laoreet. Maecenas eu tempor orci, et feugiat metus. Ut consequat libero sed bibendum mollis. Cras in ipsum id purus volutpat maximus ac commodo sem. Pellentesque magna eros, facilisis in urna id, luctus suscipit turpis. ',
        volunteerBenefitsDescription: 'Donec dignissim augue et est viverra blandit. Aliquam erat volutpat. ',
        projectType: ProjectType.RECURRING,
        time: '09:00',
        address: '129 Jogger Road, #01-03, Singapore 185019',
        region: ProjectRegion.WEST,
        state: ProjectState.REJECTED,
        rejectionReason: 'Project does not have much meaning and the issues addressed do not match the title. Sed ut porta leo, et vulputate urna. Nunc at neque ultrices urna sodales dictum non ut neque. Vestibulum rhoncus felis ac metus auctor, eu porta tortor ultrices.',
        frequency: ProjectFrequency.A_FEW_TIMES_A_YEAR,
      },
      {
        title: 'Use Less Straws',
        description: 'Consciously reduce the usage of straws.',
        volunteerSignupUrl: '',
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WASTE, IssueAddressed.GREEN_LIFESTYLE],
        volunteerRequirementsDescription: 'Integer non mi id augue fermentum hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
        volunteerBenefitsDescription: 'Save sea animals! Integer non mi id augue fermentum hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
        projectType: ProjectType.RECURRING,
        region: ProjectRegion.WEST,
        state: ProjectState.PENDING_APPROVAL,
        frequency: ProjectFrequency.EVERY_DAY,
      },
      {
        title: 'Eco Film Festival 2',
        description: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.',
        volunteerSignupUrl: 'https://www.lipsum.com/feed/html',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.AIR_QUALITY, IssueAddressed.FOOD_AND_AGRICULTURE, IssueAddressed.CLIMATE, IssueAddressed.BIODIVERSITY, IssueAddressed.WATER],
        volunteerRequirementsDescription: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. ',
        volunteerBenefitsDescription: 'The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
        projectType: ProjectType.RECURRING,
        time: '09:00',
        region: ProjectRegion.WEST,
        state: ProjectState.PENDING_APPROVAL,
        frequency: ProjectFrequency.A_FEW_TIMES_A_YEAR,
      },
      {
        title: 'Go Vegetarian Fridays',
        description: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable.',
        volunteerSignupUrl: 'www.google.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.GREEN_LIFESTYLE, IssueAddressed.LAND_AND_NOISE_POLLUTION],
        volunteerRequirementsDescription: 'Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        volunteerBenefitsDescription: 'It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.',
        projectType: ProjectType.RECURRING,
        time: '09:00',
        region: ProjectRegion.WEST,
        state: ProjectState.PENDING_APPROVAL,
        frequency: ProjectFrequency.ONCE_A_WEEK,
      },
      {
        title: 'Stay at an Eco Lodge',
        description: 'Maecenas a tristique sapien. Proin luctus tincidunt mi, et laoreet ex varius congue. Praesent risus nulla, vulputate eu cursus ut, condimentum vitae risus.',
        volunteerSignupUrl: 'https://stackoverflow.com/',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.AWARENESS_AND_EDUCATION, IssueAddressed.CONSERVATION],
        volunteerRequirementsDescription: 'Must not be afraid to be bitten by mosquitoes and leeches.',
        volunteerBenefitsDescription: 'You will be rewarded with nature! <3s',
        projectType: ProjectType.EVENT,
        time: '09:00',
        region: ProjectRegion.WEST,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2020, 2, 21),
        endDate: new Date(2020, 2, 28),
      },
      {
        title: 'Green Corridor Marathon',
        description: 'Start the new year by running a 24 km marathon to raise funds for a green cause!',
        volunteerSignupUrl: 'facebook.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WASTE, IssueAddressed.GREEN_LIFESTYLE],
        volunteerRequirementsDescription: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.',
        volunteerBenefitsDescription: 'Sed ut porta leo, et vulputate urna. Nunc at neque ultrices urna sodales dictum non ut neque. Vestibulum rhoncus felis ac metus auctor, eu porta tortor ultrices. Donec eleifend enim eu est commodo venenatis. Proin lacus erat, fringilla et tempus et, porta at tellus. Donec pharetra volutpat nisi sit amet accumsan.',
        projectType: ProjectType.EVENT,
        time: '07:00',
        region: ProjectRegion.WEST,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2018, 1, 1),
        endDate: new Date(2018, 1, 1),
      },
      {
        title: 'Have you ever wondered how NEWater made?',
        description: 'Learn how NEWater is made by visiting PUB\'s desalination plant!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.CONSERVATION, IssueAddressed.WATER],
        volunteerRequirementsDescription: 'Nullam accumsan mi elit, sit amet ultricies leo sagittis a. Vestibulum commodo aliquet purus, vitae gravida mi ornare at. Suspendisse lobortis turpis ante, gravida bibendum mauris mattis ut. Integer non mi id augue fermentum hendrerit. ',
        volunteerBenefitsDescription: 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
        projectType: ProjectType.EVENT,
        time: '15:00',
        region: ProjectRegion.WEST,
        address: 'NEWater Building, 831 Townsend Drive, Singapore 102491',
        state: ProjectState.APPROVED_INACTIVE,
        startDate: new Date(2018, 10, 1),
        endDate: new Date(2018, 10, 1),
      },
      {
        title: 'A visit to Singapore\'s Countryside',
        description: 'Visit the Kranji Countryside with us! Enjoy a walk at Sungei Buloh Nature Reserve, buy some new year plants or some aquarium fishes and have lunch at Bollywood Veggies!',
        volunteerSignupUrl: 'twitter.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.FOOD_AND_AGRICULTURE, IssueAddressed.GREEN_LIFESTYLE, IssueAddressed.PRODUCTION_AND_CONSUMPTION],
        volunteerRequirementsDescription: 'Mauris tempor sapien nisi, scelerisque iaculis dolor dictum quis. Maecenas ultricies est odio, interdum maximus felis euismod non.',
        volunteerBenefitsDescription: 'Proin lacus erat, fringilla et tempus et, porta at tellus. Donec pharetra volutpat nisi sit amet accumsan.',
        projectType: ProjectType.EVENT,
        time: '07:00',
        region: ProjectRegion.NORTH,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 2, 1),
        endDate: new Date(2019, 2, 1),
      },
      {
        title: 'Gardens By the Bay Excursion',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.SPORTS_AND_RECREATION, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 1',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WASTE, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 2',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WATER, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 3',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WATER, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 4',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 5',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.AIR_QUALITY, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 6',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.AWARENESS_AND_EDUCATION, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 7',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.BIODIVERSITY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 8',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.BIODIVERSITY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 9',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.CLIMATE],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 10',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.CONSERVATION],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 11',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.ENERGY, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 12',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.FOOD_AND_AGRICULTURE, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 13',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.GREEN_LIFESTYLE, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 14',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.LAND_AND_NOISE_POLLUTION],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 15',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.PLANNING_AND_TRANSPORTATION, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 16',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.PRODUCTION_AND_CONSUMPTION, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 17',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.OTHER, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 18',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.SPORTS_AND_RECREATION, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 19',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
      {
        title: 'Gardens By the Bay Excursion 20',
        description: 'Join us to learn about climate change and green technologies used at the Gardens By the Bay Conservatories! Suitable for both young and old!',
        volunteerSignupUrl: 'github.com',
        volunteerRequirements: volunteerRequirementAttributes,
        projectOwner: projectOwner.id,
        issuesAddressed: [IssueAddressed.WATER, IssueAddressed.GREEN_TECHNOLOGY],
        volunteerRequirementsDescription: 'Aliquam eget feugiat sem. Etiam tempus venenatis malesuada. Quisque sagittis lorem at augue feugiat hendrerit.',
        volunteerBenefitsDescription: 'Duis tincidunt mattis congue. Vivamus a vestibulum tellus. Morbi ac congue felis. Nunc mattis iaculis lacus sed tincidunt.',
        projectType: ProjectType.EVENT,
        time: '11:00',
        region: ProjectRegion.CENTRAL,
        state: ProjectState.APPROVED_ACTIVE,
        startDate: new Date(2019, 5, 20),
        endDate: new Date(2019, 5, 20),
      },
    ];

    await seedData(projectAttributes, Project, 'project');
  })
  .catch((err) => {
    console.log(`error: ${err}`);
  })
  .finally(() => {
    closeMongooseConnection();
  });
