export const ProjectFrequency = {
  EVERY_DAY: 'EVERY_DAY',
  A_FEW_TIMES_A_WEEK: 'A_FEW_TIMES_A_WEEK',
  ONCE_A_WEEK: 'ONCE_A_WEEK',
  FORTNIGHTLY: 'FORTNIGHTLY',
  A_FEW_TIMES_A_MONTH: 'A_FEW_TIMES_A_MONTH',
  ONCE_A_MONTH: 'ONCE_A_MONTH',
  A_FEW_TIMES_A_YEAR: 'A_FEW_TIMES_A_YEAR',
  ONCE_A_YEAR: 'ONCE_A_YEAR',
};
